AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  key: 
    Type: String
  value:
    Type: String  
  roleArn:
    Type: String

Resources:
  Application:
    Type: AWS::CodeDeploy::Application
    Properties:
        ApplicationName: "csye6225-webapp"     
        ComputePlatform: Server
  DeploymentGroup: 
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      ApplicationName: "csye6225-webapp"
      DeploymentGroupName: "csye6225-webapp-deployment"
      DeploymentConfigName: "CodeDeployDefault.AllAtOnce"
      AutoRollbackConfiguration:
        Enabled: True
        Events: 
         - "DEPLOYMENT_FAILURE"
      DeploymentStyle:
        DeploymentOption: "WITHOUT_TRAFFIC_CONTROL"
        DeploymentType: "IN_PLACE"
      Ec2TagSet:
        Ec2TagSetList: 
          -Ec2TagGroup:
            -Key: !Sub ${key}
            -Value: !Sub ${value}
            -Type: "KEY_AND_VALUE"
      ServiceRoleArn: !Sub ${roleArn}